#Server Properties
server:
  port: 8080

#Spring Properties
spring:
  datasource:
    driver-class-name: org.postgresql.Driver

#Prometheus
management:
  server:
    port: 8081
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "metrics"
          - "actuator"
  metrics:
    export:
      prometheus:
        enabled: true