#Spring Properties
spring:
  datasource:
    url: jdbc:postgresql://127.1:5432/helpcar-customer-local?schema=helpcar_customer
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    schemas: helpcar_customer
    url: jdbc:postgresql://127.1:5432/helpcar-customer-local
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    baseline-version: 1